### PR TITLE
Fix Error: You may need an appropriate loader to handle this file type.

### PR DESCRIPTION
**Pull request by lrojas94**
Done:
* Fix error
* Update dependencies
* Added propper development mode
* Fix build
* Code cleanup

Code had a few problems worth noting, which were causing the error stated at the title:
* You were pointing the `main` file to the `app.js` bundle file. Since this is a node module, you should make a bundle of your exported file (the component) only.
* Inheritance was *not* properly setup. You were missing the `props` in the constructor for a React Component.

### CODE REVIEW

**Comment by Tinusw** [comment]
when are we planning to get this merged?

**Comment by lrojas94** [comment]
Just waiting for @BosNaufal to approve it... but it seems he hasn't been available.

**Comment by Tinusw** [comment]
let us know if you need help @BosNaufal !

**Comment by lrojas94** [comment]
@BosNaufal please rever the last commit, as it was used to re-publish the package (which I'm sure you don't want over here!).

**Comment by BosNaufal** [comment]
Thanks a lot! @lrojas94 @Tinusw 
Not sure can do this without you guys~  https://github.com/BosNaufal/react-file-base64/commit/63dc7699111888d7b3fa754de27e2f8d0effe1d4

**Pull request merged**
